### ISSUE TITLE
Unicode character in commit message become irrecognizable code

### ISSUE THREAD

**Issue by zisten** [ioanrogers/Dist-Zilla-Plugin-ChangelogFromGit-CPAN-Changes#19]
Thanks for your work, it's awesome.

The problem caused when I use Chinese language in commit messages, in `Changes` it shows:
```
 - Ã¥Â®Â<U+008C>Ã¦Â<U+0088>Â<U+0090>ExporterÃ§Â<U+009A>Â<U+0084>Ã
```

Best.

**Comment by ioanrogers** [comment]
What version are you using? This should have been fixed in 0.0.14 (#15) if your commit messages are in utf8.

**Comment by zisten** [comment]
@ioanrogers , there's a simple git repo that will show the case:

https://github.com/zisten/Test-BBBBB.git

Close the repo, type `dzil build`, and the `Changes` file will show the details.

It also shows another problem(maybe?):

when commit with '-', the changes only show the message after '-'.

**Comment by ioanrogers** [comment]
Thanks. I've uploaded a couple of screenshots of my test. It is showing the Chinese characters just fine. Could it be your terminal or locale settings? Thanks

![screenshot from 2015-06-02 16-58-24](https://cloud.githubusercontent.com/assets/218970/7949967/fe10a7a2-0948-11e5-967f-894d46310a1e.png)
![screenshot from 2015-06-02 16-59-17](https://cloud.githubusercontent.com/assets/218970/7949968/fe12703c-0948-11e5-8c4e-254df7840607.png)

**Comment by zisten** [comment]
Sorry for late. I've updated my perl modules by `cpan-outdated`, and the problem disappeared. Thank you for your work.
