### ISSUE TITLE
Tests fail (with recent Dist::Zilla?)

### ISSUE THREAD

**Issue by eserte** [ioanrogers/Dist-Zilla-Plugin-ChangelogFromGit-CPAN-Changes#24]
See subject. Statistical analysis suggests that Dist::Zilla 6+ could cause the problem. See: http://analysis.cpantesters.org/solved?distv=Dist-Zilla-Plugin-ChangelogFromGit-CPAN-Changes-0.109

**Comment by ioanrogers** [comment]
Thanks for the report, @eserte :+1:
